### ISSUE TITLE
Allow the unauthorised handler to be configured when plugged

### ISSUE THREAD

**Issue by frm** [subvisual/dictator#25]
Currently, you can only configure the unauthorised handler globally by setting it in `config/*.exs` files.

However, it makes sense to have the following scenario:

```elixir
pipeline :api do
  plug Dictator, unauthorized_handler: JSONApiHandler
end

pipeline :browser do
  plug Dictator, unauthorized_handler: Render404HTML
end
```

We should add the unauthorized_handler to the `opts` sent to the plug.

**Comment by naps62** [comment]
true, but I think the way to go would be to have all options in general be configurable that way, not just a specific one.

It should just be a matter of merging the arguments with the global defaults

**Comment by frm** [comment]
Are there any others that are not configurable this way?

**Comment by naps62** [comment]
don't know. I'm just clarifying that this issue shouldn't be about implementing specifically the `unauthorized_handler`, but to check just that

**Comment by joseemds** [comment]
Hi! Can i work on this?

**Comment by frm** [comment]
@joseemds go for it!
